language: generic
sudo: required  
services:
  - docker

before_install:
  - docker build -t kiamso/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kiamso/react-test npm test

after_success:
  - docker build -t kiamso/multi-client ./client
  - docker build -t kiamso/multi-nginx ./nginx
  - docker build -t kiamso/multi-server ./server
  - docker build -t kiamso/multi-worker ./worker
#log in into locker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#take those images and push them to docker hub
  - docker push kiamso/multi-client
  - docker push kiamso/multi-nginx
  - docker push kiamso/multi-server
  - docker push kiamso/multi-worker